version: "3.8"
services:
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
      - ~/.aws:/root/.aws:ro
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
